services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dino_admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: dino-brief
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
